name: Build

# Events that trigger workflows - https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
  push:
    branches: [ "main" ]
  pull_request: 

jobs: 
  Mulesoft:
    uses: btfacrm/common-devops/.github/workflows/mule-build.yml@main
    secrets: inherit